### ISSUE TITLE
License

### ISSUE THREAD

**Issue by shiffman** [shiffman/Open-Source-Studio-Playground#1]
I forgot to include a license

**Comment by shiffman** [comment]
The license included for now is MIT, but discussion is welcome here in this thread!

**Comment by vince19972** [comment]
I found [this post](https://medium.freecodecamp.org/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94) to be a great introduction to different types of licenses. Sharing with everyone!

**Comment by shiffman** [comment]
Let's continue this discussion in #22.
