### ISSUE TITLE
Readings

### ISSUE THREAD

**Issue by nicolaspe** [shiffman/Open-Source-Studio-Playground#15]
Are we supposed to do the reading of each week before class and discuss them in class, or after class and just reflect on them on our blog posts?

**Comment by shiffman** [comment]
Good question! The "week 1" readings are meant to be done after last week's class and before next week's . . . and discussed in class / reflected on the blog! But I'm open to other ways of doing it!

**Comment by tinkrmind** [comment]
I prefer in class discussions! So long as we can **self-regulate** to short discussions 😸

**Comment by shiffman** [comment]
Hopefully this is clear now? I am closing this issue but happy to continue to discuss, feel free to re-open!
