### ISSUE TITLE
Having trouble with PR

### ISSUE THREAD

**Issue by kriziaf** [shiffman/Open-Source-Studio-Playground#18]
I wanted to add my homework submission but it wasn't working? 
Krizia Fernando [Organizing: the "O" in Open Source](https://kernfern.wordpress.com/2018/09/11/open-source-drives-us-forward/)

**Comment by RomolaZhang** [comment]
You can try to fork the whole repo first, make changes to it and then start a new pull request.

**Comment by kriziaf** [comment]
Thanks, @RomolaZhang! I missed day one of class. Any chance you are on the floor right now? Should I have the repo on my desktop?

**Comment by shiffman** [comment]
Don't worry @kriziaf we'll be going over and practicing this in class today too! Leaving it here for now is a-ok! (I will also be in the classroom early soon to set-up and can help.)

**Comment by shiffman** [comment]
Closing this issue as I think it is resolved? @kriziaf you are welcome to ask if you have more questions!
