### ISSUE TITLE
Image captions for accessiblility

### ISSUE THREAD

**Issue by alicehgsun** [shiffman/Open-Source-Studio-Playground#19]
For assignment, it says "be mindful of including image captions for accessibility." Is this note specifically for Medium users?

**Comment by js6450** [comment]
I think it's good to use the <img> alt tag for providing a text alternate of an image in general.

**Comment by shiffman** [comment]
Yes, best practice for accessibility is to use the alt tag for all images:

```html
<img src="rainbow.jpg" alt="A rainbow">
```

However, from what I understand medium posts don't easily support this but you can use the caption area as an alternative.

Hope this covers it!
