### ISSUE TITLE
Contribution besides fork & PR

### ISSUE THREAD

**Issue by D31F43** [shiffman/Open-Source-Studio-Playground#6]
Hi Daniel (@shiffman),

I think maybe you can add students into collaborators list, so that besides simply `fork` and `pull request` we can also create new branches (even mark tags) to explore more git / github features in this repo.

By knowing difference of PR from own forked repo or from new branch, it is easier to demonstrate concept of open source contribution and open source distribution process.

Best

**Comment by shiffman** [comment]
Yes, this is great feedback! I'll go over this at the start of class next week and make this change when do our first "triage"!

**Comment by shiffman** [comment]
Ok, I'm now adding everyone as members of the org!
