### ISSUE TITLE
Should we category labels?

### ISSUE THREAD

**Issue by WenheLI** [shiffman/Open-Source-Studio-Playground#7]
Hi all,

I am wondering if we can put some labels first on our issues so that we can know easily about what is going on exactly.

**Comment by shiffman** [comment]
Yes, let's discuss what labels would be appropriate in this thread and we'll add them in class next week!

**Comment by alicehgsun** [comment]
I would love to know this as well! 😢

**Comment by shiffman** [comment]
Ok, I started adding new labels and going through our issues! As a "member" do you have privileges to create and assign labels? Closing as I think we can re-open new issues for any specific discussion?
